language: c
dist: xenial

os:
  - linux
  # (maybe also osx, but that will require convering all of the apt packages...)

before_install:
  - "sudo apt-get update"

install:
  # Prerequisites
  - "sudo apt-get install autogen gobjc gobjc++ gobjc-multilib gobjc++-multilib libopts25 libopts25-dev texinfo flex flex-doc pax libcurses-perl dejagnu expect libexpect-perl guile-1.8 guile-1.8-dev guile-1.8-libs tcl-tclreadline m4 xutils-dev libgcj-common ecj-gcj gfortran gfortran-multilib gccgo gccgo-multilib libdmalloc-dev libdmalloc5 gnulib fastjar gcj-jre gcj-jdk autopoint gperf help2man libextutils-f77-perl"

# set up env
before_script: test -e ./.profile_generic && source ./.profile_generic

# try to build
script: cd src && ./configure --with-x --disable-werror --disable-opts-test --enable-64-bit-bfd --enable-silent-rules --with-system-zlib && make V=0

compiler:
  - clang
  - gcc

after_success: pwd
after_failure: find . -name config.log | xargs cat | grep -i error | sort | uniq
