name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: 'Debug failures'
        if: failure()
        run: |
          if test -d ./log/; then ls ./log/; fi
          if test -d ./logs/; then ls ./logs/; fi
          pwd && ls
